ktor:
  application:
    modules:
      - com.pedrorau.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
  development: true

database:
  driver: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/events_db?useSSL=false"
  user: "root"
  password: "root"
  poolSize: 3